# Generated by Django 5.2.13 on 2026-05-02 06:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='UDF, LDF, NDA, OTH', max_length=3, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('color_code', models.CharField(default='#808080', help_text='Primary hex color', max_length=7)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='ECI constituency number (1-140)', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('reserved_category', models.CharField(choices=[('GEN', 'General'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe')], default='GEN', max_length=3)),
                ('parliament_constituency', models.CharField(blank=True, help_text='LS constituency this AC falls under', max_length=100)),
                ('region', models.CharField(blank=True, choices=[('north', 'North (Malabar)'), ('central_north', 'Central North'), ('south_central', 'South Central'), ('south', 'South (Travancore)')], help_text='Geographic region for UI grouping', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Constituencies',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='DataSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(help_text='meta, constituencies, results, historical', max_length=50, unique=True)),
                ('last_exported', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('record_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(help_text='Display order from north to south')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('vote_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_winner', models.BooleanField(default=False)),
                ('is_leading', models.BooleanField(default=False)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_2026', to='core.constituency')),
            ],
            options={
                'ordering': ['-votes'],
            },
        ),
        migrations.AddField(
            model_name='constituency',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='constituencies', to='core.district'),
        ),
        migrations.CreateModel(
            name='ECIScrapeRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('rounds_completed', models.IntegerField(default=0)),
                ('total_rounds', models.IntegerField(default=0)),
                ('is_final', models.BooleanField(default=False)),
                ('eci_last_updated', models.CharField(blank=True, max_length=100)),
                ('raw_candidates', models.JSONField(default=list)),
                ('match_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('MATCHED', 'Matched & Committed'), ('PARTIAL', 'Partially Matched'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eci_raw_results', to='core.constituency')),
            ],
            options={
                'verbose_name': 'ECI Raw Scrape',
                'verbose_name_plural': 'ECI Raw Scrapes',
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='ECICandidateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eci_name', models.CharField(max_length=200)),
                ('eci_party', models.CharField(max_length=200)),
                ('eci_total_votes', models.IntegerField(default=0)),
                ('eci_vote_percentage', models.FloatField(default=0.0)),
                ('eci_is_leading', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_nota', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eci_matches', to='core.candidate')),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.constituency')),
                ('scrape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.eciscraperaw')),
            ],
            options={
                'ordering': ['-eci_total_votes'],
            },
        ),
        migrations.CreateModel(
            name='LiveResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Counting Not Started'), ('IN_PROGRESS', 'Counting In Progress'), ('COMPLETED', 'Counting Completed'), ('RESULT_DECLARED', 'Result Declared')], default='NOT_STARTED', max_length=20)),
                ('total_electors', models.IntegerField(default=0)),
                ('votes_polled', models.IntegerField(default=0)),
                ('votes_counted', models.IntegerField(default=0)),
                ('valid_votes', models.IntegerField(default=0)),
                ('rejected_votes', models.IntegerField(default=0)),
                ('rounds_completed', models.IntegerField(default=0)),
                ('total_rounds', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_results', to='core.constituency')),
            ],
            options={
                'ordering': ['constituency__number'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Canonical abbreviation (INC, CPI_M, BJP, etc)', max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('color_code', models.CharField(default='#808080', help_text='Hex color for charts', max_length=7)),
                ('alliance', models.ForeignKey(help_text='Default / 2026 alliance', on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='core.alliance')),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'ordering': ['alliance__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalResult2021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField(blank=True, help_text='Serial number on ballot', null=True)),
                ('candidate_name', models.CharField(max_length=200)),
                ('sex', models.CharField(blank=True, max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, help_text='GENERAL, SC, ST', max_length=20)),
                ('party_code', models.CharField(help_text='Original ECI party code (legacy)', max_length=50)),
                ('party_symbol', models.CharField(blank=True, max_length=200)),
                ('general_votes', models.IntegerField(default=0)),
                ('postal_votes', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField()),
                ('vote_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_winner', models.BooleanField(default=False)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_2021', to='core.constituency')),
                ('party', models.ForeignKey(blank=True, help_text='Canonical party (FK)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results_2021', to='core.party')),
            ],
            options={
                'verbose_name': '2021 LA Result',
                'verbose_name_plural': '2021 LA Results',
                'ordering': ['constituency__number', '-total_votes'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalResult2016Full',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('sex', models.CharField(blank=True, max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, help_text='GEN, SC, ST', max_length=20)),
                ('party_code', models.CharField(help_text='Original ECI party code (legacy)', max_length=50)),
                ('general_votes', models.IntegerField(default=0)),
                ('postal_votes', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('vote_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_electors', models.IntegerField(default=0)),
                ('total_votes_polled', models.IntegerField(default=0)),
                ('is_winner', models.BooleanField(default=False)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_2016_full', to='core.constituency')),
                ('party', models.ForeignKey(blank=True, help_text='Canonical party (FK)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results_2016', to='core.party')),
            ],
            options={
                'verbose_name': '2016 LA Result (Full)',
                'verbose_name_plural': '2016 LA Results (Full)',
                'ordering': ['constituency__number', '-total_votes'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalResult2011',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField(blank=True, null=True)),
                ('candidate_name', models.CharField(max_length=200)),
                ('sex', models.CharField(blank=True, max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('party_code', models.CharField(help_text='Original ECI party code (legacy)', max_length=50)),
                ('party_symbol', models.CharField(blank=True, max_length=200)),
                ('general_votes', models.IntegerField(default=0)),
                ('postal_votes', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('vote_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_electors', models.IntegerField(default=0)),
                ('is_winner', models.BooleanField(default=False)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_2011', to='core.constituency')),
                ('party', models.ForeignKey(blank=True, help_text='Canonical party (FK)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results_2011', to='core.party')),
            ],
            options={
                'verbose_name': '2011 LA Result',
                'verbose_name_plural': '2011 LA Results',
                'ordering': ['constituency__number', '-total_votes'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalResult2006',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField(blank=True, null=True)),
                ('candidate_name', models.CharField(max_length=200)),
                ('sex', models.CharField(blank=True, max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('party_code', models.CharField(help_text='Original ECI party code (legacy)', max_length=50)),
                ('party_symbol', models.CharField(blank=True, max_length=200)),
                ('general_votes', models.IntegerField(default=0)),
                ('postal_votes', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('vote_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_electors', models.IntegerField(default=0)),
                ('is_winner', models.BooleanField(default=False)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_2006', to='core.constituency')),
                ('party', models.ForeignKey(blank=True, help_text='Canonical party (FK)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results_2006', to='core.party')),
            ],
            options={
                'verbose_name': '2006 LA Result',
                'verbose_name_plural': '2006 LA Results',
                'ordering': ['constituency__number', '-total_votes'],
            },
        ),
        migrations.CreateModel(
            name='ConstituencyMeta2021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_electors', models.IntegerField()),
                ('winner_name', models.CharField(blank=True, max_length=200)),
                ('winner_party_code', models.CharField(blank=True, help_text='Legacy winner party code', max_length=50)),
                ('margin', models.IntegerField(default=0)),
                ('constituency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_2021', to='core.constituency')),
                ('winner_party', models.ForeignKey(blank=True, help_text='Winning party FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.party')),
            ],
            options={
                'verbose_name': '2021 Constituency Metadata',
                'verbose_name_plural': '2021 Constituency Metadata',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates_2026', to='core.party'),
        ),
        migrations.CreateModel(
            name='CandidateAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eci_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_aliases', to='core.candidate')),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.constituency')),
            ],
            options={
                'verbose_name': 'Candidate Alias',
                'verbose_name_plural': 'Candidate Aliases',
                'unique_together': {('constituency', 'eci_name')},
            },
        ),
        migrations.CreateModel(
            name='ParliamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2019, '2019'), (2024, '2024')])),
                ('parliament_constituency', models.CharField(help_text='LS constituency name', max_length=100)),
                ('udf_votes', models.IntegerField()),
                ('ldf_votes', models.IntegerField()),
                ('nda_votes', models.IntegerField()),
                ('lead_alliance', models.CharField(max_length=3)),
                ('runnerup_alliance', models.CharField(max_length=3)),
                ('margin', models.IntegerField()),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parliament_results', to='core.constituency')),
            ],
            options={
                'verbose_name': 'Parliament Result (AC Level)',
                'verbose_name_plural': 'Parliament Results (AC Level)',
                'ordering': ['year', 'constituency__number'],
                'unique_together': {('year', 'constituency')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalResult2016',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_candidate', models.CharField(max_length=200)),
                ('winner_party_code', models.CharField(blank=True, help_text='Legacy', max_length=20)),
                ('winner_alliance_code', models.CharField(blank=True, help_text='Legacy', max_length=3)),
                ('winner_votes', models.IntegerField()),
                ('winner_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('runnerup_candidate', models.CharField(max_length=200)),
                ('runnerup_party_code', models.CharField(blank=True, help_text='Legacy', max_length=20)),
                ('runnerup_alliance_code', models.CharField(blank=True, help_text='Legacy', max_length=3)),
                ('runnerup_votes', models.IntegerField()),
                ('runnerup_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('margin', models.IntegerField()),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_2016', to='core.constituency')),
                ('runnerup_alliance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.alliance')),
                ('winner_alliance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.alliance')),
                ('runnerup_party', models.ForeignKey(blank=True, help_text='Runner-up party FK', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runnerups_2016', to='core.party')),
                ('winner_party', models.ForeignKey(blank=True, help_text='Winner party FK', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wins_2016', to='core.party')),
            ],
            options={
                'verbose_name': '2016 LA Result',
                'verbose_name_plural': '2016 LA Results',
                'unique_together': {('constituency',)},
            },
        ),
        migrations.CreateModel(
            name='PartyAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_code', models.CharField(help_text='ECI/CSV code variant', max_length=50)),
                ('election_year', models.IntegerField(blank=True, help_text='Year-specific alias (null = universal)', null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.party')),
            ],
            options={
                'verbose_name': 'Party Alias',
                'verbose_name_plural': 'Party Aliases',
                'ordering': ['alias_code'],
                'unique_together': {('alias_code', 'election_year')},
            },
        ),
        migrations.CreateModel(
            name='PartyAllianceYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_year', models.IntegerField(help_text='Election year e.g. 2021')),
                ('election_type', models.CharField(choices=[('LA', 'Legislative Assembly'), ('LS', 'Lok Sabha')], max_length=2)),
                ('color_code', models.CharField(default='#808080', max_length=7)),
                ('alliance', models.ForeignKey(help_text='Alliance for this year', on_delete=django.db.models.deletion.PROTECT, related_name='party_years', to='core.alliance')),
                ('party', models.ForeignKey(help_text='Canonical party', on_delete=django.db.models.deletion.CASCADE, related_name='alliance_years', to='core.party')),
            ],
            options={
                'verbose_name': 'Party Alliance (by Year)',
                'verbose_name_plural': 'Party Alliances (by Year)',
                'ordering': ['election_year', 'alliance__code', 'party__code'],
                'unique_together': {('party', 'election_year', 'election_type')},
            },
        ),
    ]
