# Generated by Django 5.2.13 on 2026-04-29 03:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='ECI constituency number (1-140)', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('reserved_category', models.CharField(choices=[('GEN', 'General'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe')], default='GEN', max_length=3)),
                ('parliament_constituency', models.CharField(blank=True, help_text='LS constituency this AC falls under', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Constituencies',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='DataSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(help_text='meta, constituencies, results, historical', max_length=50, unique=True)),
                ('last_exported', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('record_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(help_text='Display order from north to south')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Party abbreviation (INC, CPI(M), BJP, etc)', max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('alliance', models.CharField(choices=[('UDF', 'United Democratic Front'), ('LDF', 'Left Democratic Front'), ('NDA', 'National Democratic Alliance'), ('OTH', 'Other')], max_length=3)),
                ('color_code', models.CharField(default='#808080', help_text='Hex color for charts', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'ordering': ['alliance', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ConstituencyMeta2021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_electors', models.IntegerField()),
                ('winner_name', models.CharField(blank=True, max_length=200)),
                ('winner_party', models.CharField(blank=True, max_length=50)),
                ('margin', models.IntegerField(default=0)),
                ('constituency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_2021', to='core.constituency')),
            ],
            options={
                'verbose_name': '2021 Constituency Metadata',
                'verbose_name_plural': '2021 Constituency Metadata',
            },
        ),
        migrations.AddField(
            model_name='constituency',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='constituencies', to='core.district'),
        ),
        migrations.CreateModel(
            name='HistoricalResult2021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField(blank=True, help_text='Serial number on ballot', null=True)),
                ('candidate_name', models.CharField(max_length=200)),
                ('sex', models.CharField(blank=True, max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, help_text='GENERAL, SC, ST', max_length=20)),
                ('party_code', models.CharField(help_text='Party abbreviation or IND/NOTA', max_length=50)),
                ('party_symbol', models.CharField(blank=True, max_length=200)),
                ('general_votes', models.IntegerField(default=0)),
                ('postal_votes', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField()),
                ('vote_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_winner', models.BooleanField(default=False)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_2021', to='core.constituency')),
            ],
            options={
                'verbose_name': '2021 LA Result',
                'verbose_name_plural': '2021 LA Results',
                'ordering': ['constituency__number', '-total_votes'],
            },
        ),
        migrations.CreateModel(
            name='LiveResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Counting Not Started'), ('IN_PROGRESS', 'Counting In Progress'), ('COMPLETED', 'Counting Completed'), ('RESULT_DECLARED', 'Result Declared')], default='NOT_STARTED', max_length=20)),
                ('total_electors', models.IntegerField(default=0)),
                ('votes_polled', models.IntegerField(default=0)),
                ('votes_counted', models.IntegerField(default=0)),
                ('valid_votes', models.IntegerField(default=0)),
                ('rejected_votes', models.IntegerField(default=0)),
                ('rounds_completed', models.IntegerField(default=0)),
                ('total_rounds', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_results', to='core.constituency')),
            ],
            options={
                'ordering': ['constituency__number'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalResult2016',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_candidate', models.CharField(max_length=200)),
                ('winner_party', models.CharField(max_length=20)),
                ('winner_alliance', models.CharField(max_length=3)),
                ('winner_votes', models.IntegerField()),
                ('winner_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('runnerup_candidate', models.CharField(max_length=200)),
                ('runnerup_party', models.CharField(max_length=20)),
                ('runnerup_alliance', models.CharField(max_length=3)),
                ('runnerup_votes', models.IntegerField()),
                ('runnerup_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('margin', models.IntegerField()),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_2016', to='core.constituency')),
            ],
            options={
                'verbose_name': '2016 LA Result',
                'verbose_name_plural': '2016 LA Results',
                'unique_together': {('constituency',)},
            },
        ),
        migrations.CreateModel(
            name='ParliamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2019, '2019'), (2024, '2024')])),
                ('parliament_constituency', models.CharField(help_text='LS constituency name', max_length=100)),
                ('udf_votes', models.IntegerField()),
                ('ldf_votes', models.IntegerField()),
                ('nda_votes', models.IntegerField()),
                ('lead_alliance', models.CharField(max_length=3)),
                ('runnerup_alliance', models.CharField(max_length=3)),
                ('margin', models.IntegerField()),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parliament_results', to='core.constituency')),
            ],
            options={
                'verbose_name': 'Parliament Result (AC Level)',
                'verbose_name_plural': 'Parliament Results (AC Level)',
                'ordering': ['year', 'constituency__number'],
                'unique_together': {('year', 'constituency')},
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('vote_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_winner', models.BooleanField(default=False)),
                ('is_leading', models.BooleanField(default=False)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_2026', to='core.constituency')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates_2026', to='core.party')),
            ],
            options={
                'ordering': ['-votes'],
                'unique_together': {('constituency', 'party')},
            },
        ),
    ]
