# Generated by Django 5.2.13 on 2026-04-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_candidate_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='alliance',
            field=models.CharField(choices=[('UDF', 'United Democratic Front'), ('LDF', 'Left Democratic Front'), ('NDA', 'National Democratic Alliance'), ('OTH', 'Other')], help_text='Default / 2026 alliance', max_length=3),
        ),
        migrations.CreateModel(
            name='PartyAllianceYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_code', models.CharField(help_text='Party code as it appears in the source data (may be a variant/alias)', max_length=50)),
                ('canonical_code', models.CharField(blank=True, help_text='Canonical party code (leave blank if same as party_code)', max_length=50)),
                ('election_year', models.IntegerField(help_text='Election year e.g. 2021')),
                ('election_type', models.CharField(choices=[('LA', 'Legislative Assembly'), ('LS', 'Lok Sabha')], max_length=2)),
                ('alliance', models.CharField(choices=[('UDF', 'United Democratic Front'), ('LDF', 'Left Democratic Front'), ('NDA', 'National Democratic Alliance'), ('OTH', 'Other')], max_length=3)),
                ('color_code', models.CharField(default='#808080', max_length=7)),
            ],
            options={
                'verbose_name': 'Party Alliance (by Year)',
                'verbose_name_plural': 'Party Alliances (by Year)',
                'ordering': ['election_year', 'alliance', 'party_code'],
                'unique_together': {('party_code', 'election_year', 'election_type')},
            },
        ),
    ]
