# Generated by Django 5.2.13 on 2026-04-29 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_party_alliance_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECIScrapeRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('rounds_completed', models.IntegerField(default=0)),
                ('total_rounds', models.IntegerField(default=0)),
                ('is_final', models.BooleanField(default=False)),
                ('eci_last_updated', models.CharField(blank=True, max_length=100)),
                ('raw_candidates', models.JSONField(default=list)),
                ('match_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('MATCHED', 'Matched & Committed'), ('PARTIAL', 'Partially Matched'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eci_raw_results', to='core.constituency')),
            ],
            options={
                'verbose_name': 'ECI Raw Scrape',
                'verbose_name_plural': 'ECI Raw Scrapes',
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='ECICandidateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eci_name', models.CharField(max_length=200)),
                ('eci_party', models.CharField(max_length=200)),
                ('eci_total_votes', models.IntegerField(default=0)),
                ('eci_vote_percentage', models.FloatField(default=0.0)),
                ('eci_is_leading', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_nota', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eci_matches', to='core.candidate')),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.constituency')),
                ('scrape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.eciscraperaw')),
            ],
            options={
                'ordering': ['-eci_total_votes'],
            },
        ),
    ]
