# Generated by Django 5.2.13 on 2026-04-30 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_eciscraperaw_ecicandidatematch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eci_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.candidate')),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.constituency')),
            ],
            options={
                'verbose_name': 'Candidate Alias',
                'verbose_name_plural': 'Candidate Aliases',
                'unique_together': {('constituency', 'eci_name')},
            },
        ),
    ]
