# Generated by Django 5.2.13 on 2026-04-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_candidatealias'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='region',
            field=models.CharField(blank=True, choices=[('north', 'North (Malabar)'), ('central_north', 'Central North'), ('south_central', 'South Central'), ('south', 'South (Travancore)')], help_text='Geographic region for UI grouping', max_length=20),
        ),
    ]
