# Generated by Django 5.2.13 on 2026-05-01 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_populate_constituency_regions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalResult2016Full',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('sex', models.CharField(blank=True, max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, help_text='GEN, SC, ST', max_length=20)),
                ('party_code', models.CharField(help_text='Normalised party code', max_length=50)),
                ('general_votes', models.IntegerField(default=0)),
                ('postal_votes', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('vote_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_electors', models.IntegerField(default=0)),
                ('total_votes_polled', models.IntegerField(default=0)),
                ('is_winner', models.BooleanField(default=False)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_2016_full', to='core.constituency')),
            ],
            options={
                'verbose_name': '2016 LA Result (Full)',
                'verbose_name_plural': '2016 LA Results (Full)',
                'ordering': ['constituency__number', '-total_votes'],
            },
        ),
    ]
